---
branches:
    only:
    - source
language: ruby
rvm:
  - 1.9.3
before_script:
- git config --global user.name "Hoat Le"
- git config --global user.email "hoatlevan@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
script: bundle exec rake generate
after_script:
- git branch --set-upstream-to=origin/master master
- bundle exec rake deploy
env:
    global:
    - GH_REPO="teracy-official/teracy-official.github.io"
    - secure: "f+g8tyvZYOYm+jUARCD5qLNMFkslYu26PwAFe8s4VzngJ2iv37T0yj5d8R40/cLIQ6LX+nHAltuJeNK786qjtiIuKuvHAypL0/3ZgVSN9XZAKnVvwh7fz7W7bETrJDkyk1WVSTini37CLSIdDS8lBg4iKHAhSuD35FZviuf/CbY="
